version: '3.6'
services:
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 3000:3000
    
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    restart: always
    ports:
      - 4000:4000
